version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: micro
      POSTGRES_USER: micro
      POSTGRES_PASSWORD: micro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    depends_on: [postgres]
    environment:
      DB_DSN: "host=postgres user=micro password=micro dbname=micro sslmode=disable"
      GRPC_PORT: "50051"
      HTTP_PORT: "8081"
    ports:
      - "8081:8081"
      - "50051:50051"

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    depends_on: [postgres]
    environment:
      DB_DSN: "host=postgres user=micro password=micro dbname=micro sslmode=disable"
      GRPC_PORT: "50052"
      HTTP_PORT: "8082"
    ports:
      - "8082:8082"
      - "50052:50052"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    depends_on: [postgres]
    environment:
      DB_DSN: "host=postgres user=micro password=micro dbname=micro sslmode=disable"
      GRPC_PORT: "50053"
      HTTP_PORT: "8083"
    ports:
      - "8083:8083"
      - "50053:50053"

volumes:
  pgdata:
